services:

  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    restart: always

  celery_beat:
    build: .
    command: celery -A celery_worker beat --loglevel=INFO -s ./celery_app/celerybeat-schedule
    env_file:
      - .env

  celery_schedules_tasks_worker:
    build: .
    command: celery -A celery_worker worker -P gevent -Q schedules-tasks
    depends_on:
      - celery_beat
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A celery_worker worker -P gevent -Q scraping-queue
    depends_on:
      - app
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2   # Workers containers dedicated for "scraping-queue" tasks processing
